### ISSUE TITLE
Will this work when we have automation suite in separate repo and application code in separate repo 

### ISSUE THREAD

**Issue by agarwlanurag** [skippy-io/skippy#149]

**Comment by fmck3516** [comment]
Hi - two questions: 
- Do your tests and code under test run in the same JVM? 
- How does your test project reference the code under test? E.g., does your test project declare a Maven / Gradle dependency to a library that contains the code under test?

**Comment by agarwlanurag** [comment]
Hi please see my response 

- yes it is under same JVM
- no the code is hosted in QA env so for UI type testing we will open the url and perform actions.

**Comment by fmck3516** [comment]
When you say "under same JVM", which of the following do you mean:

1. The tests and the code under test run in the same process. Example: Regular JUnit test that instantiates the class under test.
2. The tests and the code under test run in different processes (potentially on different machines), but they use the same version of the JVM. Example: Selenium test that runs in JVM A that makes a HTTP call to a server that runs in JVM B.

Skippy does not support setups of type #2.
