### ISSUE TITLE
Using skippy without modifying source code (not adding PredictWithSkippy annotation to each class)

### ISSUE THREAD

**Issue by FilippoVigani** [skippy-io/skippy#161]
Is there any way to use skippy without having to change the source code? Basically having all test cases opt-out instead of opt-in, maybe with an annotation `@DontPredictWithSkippy` or something like that

**Comment by helios66** [comment]
+1 to @FilippoVigani's ask

**Comment by fmck3516** [comment]
> Is there any way to use skippy without having to change the source code? Basically having all test cases opt-out instead of opt-in, maybe with an annotation `@DontPredictWithSkippy` or something like that

You can enable Skippy without changing the source code if you use JUnit 5: https://www.skippy.io/docs/#automatic-enablement

Your suggestion to add a annotation to exclude certain tests makes sense (I thought about this already). I will add this feature.

**Comment by pjmartos** [comment]
@fmck3516 We already implemented an include list / exclude list in our forked version of skippy (unfortunately we had to retrofit it so it would be compatible with Java 11).

The idea is to start supporting `<includes>` and `<excludes>` configuration properties similarly to what the `maven-compiler-plugin` supports. These properties would accept zero or more regular expressions to specify what files to take into account for TIA purposes.

Unless explicitly set, we're honouring the default `<includes>` of `maven-surefire-plugin` as the `<includes>` for `skippy-maven`, and using the default `<includes>` of `maven-failsafe-plugin` as the `<excludes>` for `skippy-maven`. We've recently started our TIA journey and still don't feel adventurous enough to also skip integration tests 😄

The reason why we decided to go with regexes for deciding if a given class should be taken into account for TIA is that at that point we only have the class name available, so adding code for supporting something more Maven-friendly such as ant path matchers would probably be a bit wasteful.

Please let me know if this is something that you'd like to see being contributed to the official project and I'll prepare a PR for it.

Thanks.

**Comment by fmck3516** [comment]
> Please let me know if this is something that you'd like to see being contributed to the official project and I'll prepare a PR for it.
Please! I would love to learn more about how you did that.

**Comment by fmck3516** [comment]
This request has been implemented in version 0.0.23 which is now available in Gradle's Plugin Portal and Maven Central.

Relevant documentation:

- https://www.skippy.io/docs/#automatic-enablement
- https://www.skippy.io/docs/#opt-out-mechanism
