### ISSUE TITLE
Some tests in nested classes are not exercised when changing related production code not exercised by the tests' top-level class

### ISSUE THREAD

**Issue by pjmartos** [skippy-io/skippy#163]
Skippy appears to not be taking into account that test classes may contain nested classes (e.g. classes annotated with `@Nested`) that in turn may contain test methods of their own (it is not mandatory, but it is usually the case).

Worts case scenario, if the top-level class itself doesn't exercise a production class that has changed, none of the tests would be executed, even if some of the nested classes of that test class do. The net result is that the change in the production class would be undetected.

**Comment by fmck3516** [comment]
Thank you for your report. I was able to re-produce the issue.

**Comment by fmck3516** [comment]
Thanks a bunch for the PR - I will review after work today.

**Comment by fmck3516** [comment]
> @fmck3516 I already submitted a PR with a fix: #164, would you have any suggestions? Thanks.

I've responded in the PR.

**Comment by fmck3516** [comment]
Additional functional tests have been added in skippy-regression-suite: https://github.com/skippy-io/skippy-regression-suite/pull/3

**Comment by pjmartos** [comment]
Thanks @fmck3516!
